spring:
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:warehouse_db
    password: pass
  liquibase:
    contexts: dev
    change-log: classpath:/db/changelog/init.xml
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
jwt:
  token:
    expirationTime: 32400000